name: Deploy to tencent

on:
  push:
    branches:
      - main  # 或者你想要监控的分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.CLOUD_DEPLOY_SSH }}

    - name: Deploy to Tencent
      run: |
        ssh -o StrictHostKeyChecking=no app@81.69.45.49 "mkdir -p /home/app/hotel"
        rsync -avz --delete --exclude '.git' --exclude '.github' ./ app@81.69.45.49:/home/app/hotel/
